-- 코드를 입력하세요
SELECT A.AUTHOR_ID, A.AUTHOR_NAME, B.CATEGORY, SUM(SALES * PRICE)
FROM BOOK_SALES S LEFT JOIN BOOK B ON S.BOOK_ID = B.BOOK_ID
LEFT JOIN AUTHOR A ON B.AUTHOR_ID = A.AUTHOR_ID
WHERE YEAR(SALES_DATE) = 2022 AND MONTH(SALES_DATE) = 1
GROUP BY B.CATEGORY, A.AUTHOR_NAME
ORDER BY AUTHOR_ID ASC, CATEGORY DESC;

# SELECT INLINE.AUTHOR_ID, A.AUTHOR_NAME, INLINE.CATEGORY, INLINE.TOTAL_SALES
# FROM (
#     SELECT B.AUTHOR_ID, B.CATEGORY, SUM(B.PRICE * S.SALES) TOTAL_SALES
#     FROM BOOK_SALES S LEFT JOIN BOOK B
#     ON S.BOOK_ID = B.BOOK_ID
#     GROUP BY B.CATEGORY
# ) INLINE LEFT JOIN AUTHOR A
# ON INLINE.AUTHOR_ID = A.AUTHOR_ID
# GROUP BY AUTHOR_ID;



# SELECT B.AUTHOR_ID, B.CATEGORY, SUM(B.PRICE * S.SALES)
# FROM BOOK_SALES S LEFT JOIN BOOK B
# ON S.BOOK_ID = B.BOOK_ID
# GROUP BY B.CATEGORY