-- 코드를 입력하세요
SELECT R.CAR_ID, R.CAR_TYPE,
ROUND((R.DAILY_FEE * (1-(P.DISCOUNT_RATE/ 100)))*30, 0) AS FEE
FROM CAR_RENTAL_COMPANY_CAR R
JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN P
ON R.CAR_TYPE = P.CAR_TYPE
WHERE 
    R.CAR_TYPE IN ("세단", "SUV")
    AND
    ROUND((R.DAILY_FEE * (1-(P.DISCOUNT_RATE/ 100)))*30, 0) BETWEEN 500000 AND 2000000
    AND
    P.DURATION_TYPE = "30일 이상"
    AND
    CAR_ID NOT IN (
        SELECT H.CAR_ID 
        FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY H
        WHERE
        H.END_DATE >= "2022-11-01" AND H.START_DATE <= "2022-11-30")