-- 코드를 입력하세요
SELECT R.FOOD_TYPE, R.REST_ID, R.REST_NAME, INLINE.FAVORITES FROM REST_INFO R JOIN (
    SELECT FOOD_TYPE, MAX(FAVORITES) FAVORITES
    FROM REST_INFO
    GROUP BY FOOD_TYPE
) INLINE ON R.FOOD_TYPE = INLINE.FOOD_TYPE AND R.FAVORITES = INLINE.FAVORITES
ORDER BY R.FOOD_TYPE DESC;


# SELECT FOOD_TYPE, MAX(FAVORITES) FAVORITES
#     FROM REST_INFO
#     GROUP BY FOOD_TYPE;