-- 코드를 입력하세요
# SELECT * FROM USED_GOODS_BOARD U;

SELECT USER_ID, NICKNAME, CONCAT(CITY," ", STREET_ADDRESS1, " ",STREET_ADDRESS2) "전체주소", 
CONCAT(SUBSTR(TLNO,1,3),"-",SUBSTR(TLNO,4,4),"-",SUBSTR(TLNO,8)) 전화번호
FROM USED_GOODS_USER G JOIN (
    SELECT 
    U.WRITER_ID, COUNT(U.BOARD_ID) AS COUNT
    FROM USED_GOODS_BOARD U 
    GROUP BY WRITER_ID
    HAVING COUNT(U.BOARD_ID) >= 3
) INLINE 
ON G.USER_ID = INLINE.WRITER_ID
ORDER BY USER_ID DESC;
