-- 코드를 입력하세요

SELECT F.PRODUCT_ID, PRODUCT_NAME, (TOTAL * PRICE) AS TOTAL_SALES FROM FOOD_PRODUCT F INNER JOIN (
    SELECT PRODUCT_ID, SUM(AMOUNT) TOTAL
    FROM FOOD_ORDER 
    WHERE YEAR(PRODUCE_DATE) = 2022 AND MONTH(PRODUCE_DATE) = 5
    GROUP BY PRODUCT_ID
) INLINE
ON F.PRODUCT_ID = INLINE.PRODUCT_ID
ORDER BY TOTAL_SALES DESC, F.PRODUCT_ID ASC;
