-- 코드를 입력하세요
# SELECT J.FLAVOR
# FROM
# JULY J LEFT JOIN FIRST_HALF F
# ON F.SHIPMENT_ID = J.SHIPMENT_ID
# GROUP BY J.FLAVOR
# ORDER BY SUM(J.TOTAL_ORDER+F.TOTAL_ORDER) DESC
# LIMIT 0,3;

SELECT INLINE.FLAVOR
FROM (
    SELECT SHIPMENT_ID ,FLAVOR, SUM(TOTAL_ORDER) TOTAL_ORDER
    FROM JULY
    GROUP BY FLAVOR
) INLINE JOIN FIRST_HALF F
ON INLINE.SHIPMENT_ID = F.SHIPMENT_ID
ORDER BY (INLINE.TOTAL_ORDER + F.TOTAL_ORDER) DESC
LIMIT 0,3;



# SELECT *
# FROM FIRST_HALF F 
