-- 코드를 입력하세요


# SELECT MONTH(START_DATE), H.CAR_ID, COUNT(H.CAR_ID) RECORDS
# FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY H
# INNER JOIN (
#     SELECT CAR_ID
#     FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY 
#     WHERE MONTH(START_DATE) BETWEEN 8 AND 11
#     GROUP BY CAR_ID
#     HAVING COUNT(CAR_ID) >= 5
# ) INLINE
# ON H.CAR_ID = INLINE.CAR_ID
# GROUP BY MONTH(START_DATE), H.CAR_ID
# HAVING COUNT(START_DATE) >= 1
# ORDER BY MONTH(START_DATE) ASC, H.CAR_ID DESC;

SELECT MONTH(START_DATE), H.CAR_ID, COUNT(H.CAR_ID) FROM
CAR_RENTAL_COMPANY_RENTAL_HISTORY H
INNER JOIN (
     SELECT CAR_ID
     FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY 
     WHERE MONTH(START_DATE) BETWEEN 8 AND 11
     GROUP BY CAR_ID
     HAVING COUNT(CAR_ID) >= 5
)INLINE
ON H.CAR_ID =INLINE.CAR_ID
WHERE MONTH(START_DATE) BETWEEN 8 AND 11
GROUP BY MONTH(START_DATE), H.CAR_ID
ORDER BY MONTH(START_DATE) ASC, H.CAR_ID DESC;
