-- 코드를 입력하세요
# SELECT *
# FROM CAR_RENTAL_COMPANY_CAR C
# WHERE C.CAR_TYPE = "세단";

SELECT DISTINCT(HISTORY.CAR_ID) AS CAR_ID
FROM (
    SELECT *
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY H
    WHERE MONTH(START_DATE) = 10
) HISTORY LEFT JOIN (
    SELECT *
    FROM CAR_RENTAL_COMPANY_CAR C
    WHERE C.CAR_TYPE = "세단"
) CAR
ON HISTORY.CAR_ID = CAR.CAR_ID
WHERE CAR.CAR_ID IS NOT NULL
ORDER BY CAR_ID DESC;


# SELECT *
# FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY H
# WHERE MONTH(START_DATE) = 10;
