-- 코드를 입력하세요
SELECT CATEGORY, SUM(SALES) TOTAL_SALES FROM BOOK B INNER JOIN (    
    SELECT BOOK_ID, SUM(SALES) SALES FROM BOOK_SALES 
    WHERE YEAR(SALES_DATE) = 2022 AND MONTH(SALES_DATE) = 1
    GROUP BY BOOK_ID
) INLINE ON B.BOOK_ID = INLINE.BOOK_ID
GROUP BY CATEGORY
ORDER BY CATEGORY ASC;

