-- 코드를 입력하세요
# SELECT P.PRODUCT_ID, P.PRODUCT_NAME, P.PRICE AS MAX_PRICE 
# FROM FOOD_PRODUCT P INNER JOIN (
#     SELECT PRODUCT_ID
#     FROM FOOD_PRODUCT
#     WHERE CATEGORY IN ("과자","국","김치","식용유")
#     GROUP BY CATEGORY
#     HAVING MAX(PRICE)
# ) INLINE ON P.PRODUCT_ID = INLINE.PRODUCT_ID;

# SELECT * FROM(
    
# ) INLINE GROUP BY INLINE.CATEGORY
# HAVING INLINE.PRICE = MAX(INLINE.PRICE);

# SELECT * FROM FOOD_PRODUCT
# WHERE PRODUCT_ID = (
    
# );
# SELECT * FROM (
    
# ) INLINE JOIN FOOD_PRODUCT F ON
# INLINE.PRODUCT_ID = F.PRODUCT_ID 
# AND INLINE.MAX_PRICE = F.PRICE;
    # SELECT * FROM FOOD_PRODUCT;
    
SELECT INLINE.CATEGORY, INLINE.MAX_PRICE, P.PRODUCT_NAME FROM FOOD_PRODUCT P JOIN (
    SELECT CATEGORY, PRODUCT_NAME, PRODUCT_CD, MAX(PRICE) AS MAX_PRICE
    FROM FOOD_PRODUCT
    GROUP BY CATEGORY
) INLINE ON INLINE.MAX_PRICE = P.PRICE AND INLINE.CATEGORY = P.CATEGORY
WHERE INLINE.CATEGORY IN ("과자","국","김치","식용유")
ORDER BY MAX_PRICE DESC;


# 과자 : P0093 1950
# 국 : P0074 2900
# 김치 : P0051 19000
# 식용유 : P0014 8950